/*
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.inria.kairos.sock.ide.contentassist.antlr.internal.InternalSockParser;
import fr.inria.kairos.sock.services.SockGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class SockParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(SockGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, SockGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getIotSystemAccess().getGroup(), "rule__IotSystem__Group__0");
			builder.put(grammarAccess.getIotSystemAccess().getGroup_4(), "rule__IotSystem__Group_4__0");
			builder.put(grammarAccess.getIotSystemAccess().getGroup_4_3(), "rule__IotSystem__Group_4_3__0");
			builder.put(grammarAccess.getIotSystemAccess().getGroup_5(), "rule__IotSystem__Group_5__0");
			builder.put(grammarAccess.getIotSystemAccess().getGroup_5_3(), "rule__IotSystem__Group_5_3__0");
			builder.put(grammarAccess.getActorAccess().getGroup(), "rule__Actor__Group__0");
			builder.put(grammarAccess.getActorAccess().getGroup_4(), "rule__Actor__Group_4__0");
			builder.put(grammarAccess.getActorAccess().getGroup_5(), "rule__Actor__Group_5__0");
			builder.put(grammarAccess.getActorAccess().getGroup_6(), "rule__Actor__Group_6__0");
			builder.put(grammarAccess.getActorAccess().getGroup_7(), "rule__Actor__Group_7__0");
			builder.put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
			builder.put(grammarAccess.getResourceAccess().getGroup_4(), "rule__Resource__Group_4__0");
			builder.put(grammarAccess.getResourceAccess().getGroup_4_3(), "rule__Resource__Group_4_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getIotSystemAccess().getNameAssignment_2(), "rule__IotSystem__NameAssignment_2");
			builder.put(grammarAccess.getIotSystemAccess().getOwnedActorAssignment_4_2(), "rule__IotSystem__OwnedActorAssignment_4_2");
			builder.put(grammarAccess.getIotSystemAccess().getOwnedActorAssignment_4_3_1(), "rule__IotSystem__OwnedActorAssignment_4_3_1");
			builder.put(grammarAccess.getIotSystemAccess().getOwnedResourceAssignment_5_2(), "rule__IotSystem__OwnedResourceAssignment_5_2");
			builder.put(grammarAccess.getIotSystemAccess().getOwnedResourceAssignment_5_3_1(), "rule__IotSystem__OwnedResourceAssignment_5_3_1");
			builder.put(grammarAccess.getActorAccess().getNameAssignment_2(), "rule__Actor__NameAssignment_2");
			builder.put(grammarAccess.getActorAccess().getIsPriorityAssignment_4_1(), "rule__Actor__IsPriorityAssignment_4_1");
			builder.put(grammarAccess.getActorAccess().getProcessTimeAssignment_5_1(), "rule__Actor__ProcessTimeAssignment_5_1");
			builder.put(grammarAccess.getActorAccess().getPeriodTimeAssignment_6_1(), "rule__Actor__PeriodTimeAssignment_6_1");
			builder.put(grammarAccess.getActorAccess().getResourceAssignment_7_1(), "rule__Actor__ResourceAssignment_7_1");
			builder.put(grammarAccess.getResourceAccess().getNameAssignment_2(), "rule__Resource__NameAssignment_2");
			builder.put(grammarAccess.getResourceAccess().getActorAssignment_4_2(), "rule__Resource__ActorAssignment_4_2");
			builder.put(grammarAccess.getResourceAccess().getActorAssignment_4_3_1(), "rule__Resource__ActorAssignment_4_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private SockGrammarAccess grammarAccess;

	@Override
	protected InternalSockParser createParser() {
		InternalSockParser result = new InternalSockParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SockGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SockGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
