/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.ui;

import fr.inria.kairos.sock.ui.AbstractSockUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SockUiModule extends AbstractSockUiModule {
  public SockUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
