/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.formatting2;

import com.google.inject.Inject;
import fr.inria.kairos.sock.dsl.model.sock.Actor;
import fr.inria.kairos.sock.dsl.model.sock.IotSystem;
import fr.inria.kairos.sock.dsl.model.sock.Resource;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class SockFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private /* SockGrammarAccess */Object _sockGrammarAccess;
  
  protected void _format(final IotSystem iotSystem, @Extension final IFormattableDocument document) {
    EList<Actor> _ownedActor = iotSystem.getOwnedActor();
    for (final Actor actor : _ownedActor) {
      document.<Actor>format(actor);
    }
    EList<Resource> _ownedResource = iotSystem.getOwnedResource();
    for (final Resource resource : _ownedResource) {
      document.<Resource>format(resource);
    }
  }
  
  public void format(final Object iotSystem, final IFormattableDocument document) {
    if (iotSystem instanceof XtextResource) {
      _format((XtextResource)iotSystem, document);
      return;
    } else if (iotSystem instanceof IotSystem) {
      _format((IotSystem)iotSystem, document);
      return;
    } else if (iotSystem instanceof EObject) {
      _format((EObject)iotSystem, document);
      return;
    } else if (iotSystem == null) {
      _format((Void)null, document);
      return;
    } else if (iotSystem != null) {
      _format(iotSystem, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(iotSystem, document).toString());
    }
  }
}
