/*
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SockGrammarAccess extends AbstractGrammarElementFinder {
	
	public class IotSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.sock.Sock.IotSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIotSystemAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIotSystemKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOwnedActorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cOwnedActorAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cOwnedActorActorParserRuleCall_4_2_0 = (RuleCall)cOwnedActorAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cOwnedActorAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cOwnedActorActorParserRuleCall_4_3_1_0 = (RuleCall)cOwnedActorAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOwnedResourceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOwnedResourceAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cOwnedResourceResourceParserRuleCall_5_2_0 = (RuleCall)cOwnedResourceAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOwnedResourceAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cOwnedResourceResourceParserRuleCall_5_3_1_0 = (RuleCall)cOwnedResourceAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//IotSystem:
		//	{IotSystem}
		//	'IotSystem'
		//	name=EString
		//	'{' ('ownedActor' '{' ownedActor+=Actor ("," ownedActor+=Actor)* '}')? ('ownedResource' '{' ownedResource+=Resource
		//	("," ownedResource+=Resource)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{IotSystem} 'IotSystem' name=EString '{' ('ownedActor' '{' ownedActor+=Actor ("," ownedActor+=Actor)* '}')?
		//('ownedResource' '{' ownedResource+=Resource ("," ownedResource+=Resource)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{IotSystem}
		public Action getIotSystemAction_0() { return cIotSystemAction_0; }
		
		//'IotSystem'
		public Keyword getIotSystemKeyword_1() { return cIotSystemKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ownedActor' '{' ownedActor+=Actor ("," ownedActor+=Actor)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ownedActor'
		public Keyword getOwnedActorKeyword_4_0() { return cOwnedActorKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//ownedActor+=Actor
		public Assignment getOwnedActorAssignment_4_2() { return cOwnedActorAssignment_4_2; }
		
		//Actor
		public RuleCall getOwnedActorActorParserRuleCall_4_2_0() { return cOwnedActorActorParserRuleCall_4_2_0; }
		
		//("," ownedActor+=Actor)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//ownedActor+=Actor
		public Assignment getOwnedActorAssignment_4_3_1() { return cOwnedActorAssignment_4_3_1; }
		
		//Actor
		public RuleCall getOwnedActorActorParserRuleCall_4_3_1_0() { return cOwnedActorActorParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('ownedResource' '{' ownedResource+=Resource ("," ownedResource+=Resource)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'ownedResource'
		public Keyword getOwnedResourceKeyword_5_0() { return cOwnedResourceKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//ownedResource+=Resource
		public Assignment getOwnedResourceAssignment_5_2() { return cOwnedResourceAssignment_5_2; }
		
		//Resource
		public RuleCall getOwnedResourceResourceParserRuleCall_5_2_0() { return cOwnedResourceResourceParserRuleCall_5_2_0; }
		
		//("," ownedResource+=Resource)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//ownedResource+=Resource
		public Assignment getOwnedResourceAssignment_5_3_1() { return cOwnedResourceAssignment_5_3_1; }
		
		//Resource
		public RuleCall getOwnedResourceResourceParserRuleCall_5_3_1_0() { return cOwnedResourceResourceParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.sock.Sock.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ActorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.sock.Sock.Actor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActorKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cIsPriorityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cIsPriorityAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cIsPriorityEIntParserRuleCall_4_1_0 = (RuleCall)cIsPriorityAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cProcessTimeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cProcessTimeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cProcessTimeEIntParserRuleCall_5_1_0 = (RuleCall)cProcessTimeAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPeriodTimeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPeriodTimeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPeriodTimeEIntParserRuleCall_6_1_0 = (RuleCall)cPeriodTimeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cResourceKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cResourceAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cResourceResourceCrossReference_7_1_0 = (CrossReference)cResourceAssignment_7_1.eContents().get(0);
		private final RuleCall cResourceResourceEStringParserRuleCall_7_1_0_1 = (RuleCall)cResourceResourceCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Actor:
		//	{Actor}
		//	'Actor'
		//	name=EString
		//	'{' ('isPriority' isPriority=EInt)? ('processTime' processTime=EInt)? ('periodTime' periodTime=EInt)? ('resource'
		//	resource=[Resource|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Actor} 'Actor' name=EString '{' ('isPriority' isPriority=EInt)? ('processTime' processTime=EInt)? ('periodTime'
		//periodTime=EInt)? ('resource' resource=[Resource|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Actor}
		public Action getActorAction_0() { return cActorAction_0; }
		
		//'Actor'
		public Keyword getActorKeyword_1() { return cActorKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('isPriority' isPriority=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'isPriority'
		public Keyword getIsPriorityKeyword_4_0() { return cIsPriorityKeyword_4_0; }
		
		//isPriority=EInt
		public Assignment getIsPriorityAssignment_4_1() { return cIsPriorityAssignment_4_1; }
		
		//EInt
		public RuleCall getIsPriorityEIntParserRuleCall_4_1_0() { return cIsPriorityEIntParserRuleCall_4_1_0; }
		
		//('processTime' processTime=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'processTime'
		public Keyword getProcessTimeKeyword_5_0() { return cProcessTimeKeyword_5_0; }
		
		//processTime=EInt
		public Assignment getProcessTimeAssignment_5_1() { return cProcessTimeAssignment_5_1; }
		
		//EInt
		public RuleCall getProcessTimeEIntParserRuleCall_5_1_0() { return cProcessTimeEIntParserRuleCall_5_1_0; }
		
		//('periodTime' periodTime=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'periodTime'
		public Keyword getPeriodTimeKeyword_6_0() { return cPeriodTimeKeyword_6_0; }
		
		//periodTime=EInt
		public Assignment getPeriodTimeAssignment_6_1() { return cPeriodTimeAssignment_6_1; }
		
		//EInt
		public RuleCall getPeriodTimeEIntParserRuleCall_6_1_0() { return cPeriodTimeEIntParserRuleCall_6_1_0; }
		
		//('resource' resource=[Resource|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'resource'
		public Keyword getResourceKeyword_7_0() { return cResourceKeyword_7_0; }
		
		//resource=[Resource|EString]
		public Assignment getResourceAssignment_7_1() { return cResourceAssignment_7_1; }
		
		//[Resource|EString]
		public CrossReference getResourceResourceCrossReference_7_1_0() { return cResourceResourceCrossReference_7_1_0; }
		
		//EString
		public RuleCall getResourceResourceEStringParserRuleCall_7_1_0_1() { return cResourceResourceEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.sock.Sock.Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cResourceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cResourceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cActorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cActorAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cActorActorCrossReference_4_2_0 = (CrossReference)cActorAssignment_4_2.eContents().get(0);
		private final RuleCall cActorActorEStringParserRuleCall_4_2_0_1 = (RuleCall)cActorActorCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cActorAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cActorActorCrossReference_4_3_1_0 = (CrossReference)cActorAssignment_4_3_1.eContents().get(0);
		private final RuleCall cActorActorEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cActorActorCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Resource:
		//	{Resource}
		//	'Resource'
		//	name=EString
		//	'{' ('actor' '(' actor+=[Actor|EString] ("," actor+=[Actor|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Resource} 'Resource' name=EString '{' ('actor' '(' actor+=[Actor|EString] ("," actor+=[Actor|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Resource}
		public Action getResourceAction_0() { return cResourceAction_0; }
		
		//'Resource'
		public Keyword getResourceKeyword_1() { return cResourceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('actor' '(' actor+=[Actor|EString] ("," actor+=[Actor|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'actor'
		public Keyword getActorKeyword_4_0() { return cActorKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//actor+=[Actor|EString]
		public Assignment getActorAssignment_4_2() { return cActorAssignment_4_2; }
		
		//[Actor|EString]
		public CrossReference getActorActorCrossReference_4_2_0() { return cActorActorCrossReference_4_2_0; }
		
		//EString
		public RuleCall getActorActorEStringParserRuleCall_4_2_0_1() { return cActorActorEStringParserRuleCall_4_2_0_1; }
		
		//("," actor+=[Actor|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//actor+=[Actor|EString]
		public Assignment getActorAssignment_4_3_1() { return cActorAssignment_4_3_1; }
		
		//[Actor|EString]
		public CrossReference getActorActorCrossReference_4_3_1_0() { return cActorActorCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getActorActorEStringParserRuleCall_4_3_1_0_1() { return cActorActorEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.inria.kairos.sock.Sock.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	
	private final IotSystemElements pIotSystem;
	private final EStringElements pEString;
	private final ActorElements pActor;
	private final ResourceElements pResource;
	private final EIntElements pEInt;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SockGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pIotSystem = new IotSystemElements();
		this.pEString = new EStringElements();
		this.pActor = new ActorElements();
		this.pResource = new ResourceElements();
		this.pEInt = new EIntElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.inria.kairos.sock.Sock".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//IotSystem:
	//	{IotSystem}
	//	'IotSystem'
	//	name=EString
	//	'{' ('ownedActor' '{' ownedActor+=Actor ("," ownedActor+=Actor)* '}')? ('ownedResource' '{' ownedResource+=Resource
	//	("," ownedResource+=Resource)* '}')?
	//	'}';
	public IotSystemElements getIotSystemAccess() {
		return pIotSystem;
	}
	
	public ParserRule getIotSystemRule() {
		return getIotSystemAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Actor:
	//	{Actor}
	//	'Actor'
	//	name=EString
	//	'{' ('isPriority' isPriority=EInt)? ('processTime' processTime=EInt)? ('periodTime' periodTime=EInt)? ('resource'
	//	resource=[Resource|EString])?
	//	'}';
	public ActorElements getActorAccess() {
		return pActor;
	}
	
	public ParserRule getActorRule() {
		return getActorAccess().getRule();
	}
	
	//Resource:
	//	{Resource}
	//	'Resource'
	//	name=EString
	//	'{' ('actor' '(' actor+=[Actor|EString] ("," actor+=[Actor|EString])* ')')?
	//	'}';
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
