/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SockStandaloneSetup /* implements SockStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type SockStandaloneSetup");
  }
}
