/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SockRuntimeModule /* implements AbstractSockRuntimeModule  */{
}
