/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock;

import fr.inria.kairos.sock.AbstractSockRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SockRuntimeModule extends AbstractSockRuntimeModule {
}
