/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock;

import fr.inria.kairos.sock.SockStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SockStandaloneSetup extends SockStandaloneSetupGenerated {
  public static void doSetup() {
    new SockStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
