/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.validation;

import fr.inria.kairos.sock.validation.AbstractSockValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SockValidator extends AbstractSockValidator {
}
