/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.ide;

import com.google.inject.Injector;
import fr.inria.kairos.sock.SockStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SockIdeSetup extends SockStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from SockRuntimeModule to Module"
      + "\nType mismatch: cannot convert from SockIdeModule to Module");
  }
}
