/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.inria.kairos.sock.SockRuntimeModule;
import fr.inria.kairos.sock.SockStandaloneSetup;
import fr.inria.kairos.sock.ide.SockIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SockIdeSetup extends SockStandaloneSetup {
  @Override
  public Injector createInjector() {
    SockRuntimeModule _sockRuntimeModule = new SockRuntimeModule();
    SockIdeModule _sockIdeModule = new SockIdeModule();
    return Guice.createInjector(Modules2.mixin(_sockRuntimeModule, _sockIdeModule));
  }
}
