/**
 * generated by Xtext 2.14.0
 */
package fr.inria.kairos.sock.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SockIdeModule /* implements AbstractSockIdeModule  */{
}
